### ISSUE TITLE
Elk Alarm system not updating Alarm Panel state in Indigo plug-in

### ISSUE THREAD

**Issue by prose110** [billchurch/indigo-elk-m1-plugin#3]
Version   of Indigo: 7.2.0
Version   of macOS: Mojave   Ver 10.14.4
Version   of Firmware, Boot, and Hardware for your M1-XEP: 2.0.44;   2.0.4; 1.0
Version   of Firmware, Boot, and Hardware for your M1 panel: 5.3.10;   3.3.6; 0.13

Indigo plug-in sees my wireless sensors and immediately reacts to changes in ststus: normal, violated, trouble.

Problem is the state of the alarm panel in Indigo.  Arming the system from the Elk keypad does not change the state in Indigo.  Furthermore, I'm fully able to control the system using the server control commands in Indigo; however, the status in the panel does not change with the initial sending of the "arm" command even though the system responds appropriately.  The state of the alarm panel only changes when I click the "arm" command a second time which has the effect of disarming the system, but indicating that the panel is armed.

Thank you for your help.

**Comment by billchurch** [comment]
Well, i haven't been using Indigo for a while now, moved to Home Assistant, so difficult for me Anything in your Indigo log? 

Enable debug?

**Comment by prose110** [comment]
Bill;

Thanks for reaching out.  I’m not getting any error messages and the issue may be caused by the way I’m setting up the arming/disarm buttons.  Bottom line, the state of the system and the alarm panel are not in sync when an arm command is issued.  On the arming controls I initiatiate the arm command thorough “server action” and selecting a “state,” e.g, "Arm Stay.”  When this is activated on first push/touch of the control, the system recognizes it and goes into the Arm Stay mode.  However, the state of the Alarm Panel still shows as "Disarmed.”  Now if I touch/push the same Arm Stay control, the system becomes disarmed but the state of the Alarm Panel changes to "Arm Stay.”  I have tried many ways to get the two synchronized without success.  Please let me know what I may be doing wrong.  Thanks much.

Princeton

**Comment by billchurch** [comment]
Hmmmm... Its hard for me to think what could be the issue, I wish I still had indigo up somewhere so I could test this out, but sadly after my machine died I had it on, i gave up on it...

Have you tried the Indigo forums? I imagine there has to be a few others using this plugin...

**Comment by prose110** [comment]
Thanks again. I’ll continue my quest.  Like the Indigo app and flexibility and will work on a solution.

Regards Princeton

**Comment by prose110** [comment]
Bill;

Wanted to let you know that my problem is solved.  The Elk tech support folks identified a problem in the settings in the Elk system.  Plug-in is working great and as I envisioned and I want to again thank you for your fine work.

Princeton

**Comment by billchurch** [comment]
That’s great to hear. I’m going to try and setup a VM for this so I can help support development until someone else can take it over. Hard to troubleshoot something if I’m not able to test. :)

Can you elaborate on what the setting was for others.

**Comment by prose110** [comment]
Sure, and this setting is very important.  Without it the status of the alarm panel is not communicated real time.

"In ElkRP under Globals , G29 – G42 (Special) make sure all six “Serial Port 0 Transmit Options” are enabled and sent to the M1."

Thanks again.

Princeton

**Comment by billchurch** [comment]
Perfect, hopefully that will help others. Closing.
